# Strings, Lists, Tuples, Arrays and Dictionaries

In [2]:
%precision 4

'%.4f'

Strings

In [3]:
s1 = "My dog's name is"
s2 = "Bingo"
s3 = s1 + " " + s2
print(s3)

My dog's name is Bingo


In [4]:
s4 = '927'
s5 = 927
print(s4+str(s5))
print(int(s4)+s5)

927927
1854


In [5]:
print(s3.split())

['My', "dog's", 'name', 'is', 'Bingo']


In [6]:
print(s3.split('g'))

['My do', "'s name is Bin", 'o']


Listas

In [7]:
l1 = [0, 1, 1, 2, 3, 5, 8, 13]
l2 = [5., "girl", 2+0j,"horse",21]
print(l2[0])
print(len(l1),", ",len(l2))
print(l2[4])
print(l2[-1],", ",l2[-2])
l2[2]= l2[2]+3+1j
print(l2)

5.0
8 ,  5
21
21 ,  horse
[5.0, 'girl', (5+1j), 'horse', 21]


In [8]:
print(l1+l2)
l3 = 2*l1
print(l3,", ",len(l3))

[0, 1, 1, 2, 3, 5, 8, 13, 5.0, 'girl', (5+1j), 'horse', 21]
[0, 1, 1, 2, 3, 5, 8, 13, 0, 1, 1, 2, 3, 5, 8, 13] ,  16


Slicing lists

lista[empiezaEn:terminaAntes:salta]

In [9]:
print(l3[0:len(l3)-1])
print(l3[:])

[0, 1, 1, 2, 3, 5, 8, 13, 0, 1, 1, 2, 3, 5, 8]
[0, 1, 1, 2, 3, 5, 8, 13, 0, 1, 1, 2, 3, 5, 8, 13]


In [10]:
print(l3[::2])
print(l3[:len(l3)-1:2])
print(l3[:15:6])
print(l3[3::4])

[0, 1, 3, 8, 0, 1, 3, 8]
[0, 1, 3, 8, 0, 1, 3, 8]
[0, 8, 3]
[2, 13, 2, 13]


Creaciones de otros tipos de listas:

Caso creciente: list(range(primerNumero,ultimoNumero(no incluido),cada))

In [11]:
print(list(range(5)))
print(list(range(3,10)))
print(list(range(0,10,2)))

[0, 1, 2, 3, 4]
[3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]


Caso decreciente: list(range(primerNumero,ultimoNumero(no incluido),cada))

In [12]:
print(list(range(5,-1,-2)))

[5, 3, 1]


Algunas operaciones y construcciones 

In [13]:
from math import log
r = [1.0, 1.5,2.2]
logr = list(map(log,r))
print(r)
print(logr)
log(2.2)

[1.0, 1.5, 2.2]
[0.0, 0.4054651081081644, 0.7884573603642703]


0.7885

In [14]:
r2 = []
r2.append(1.0)
r2.append(1.5)
r2.append(2.2)
print(r2)

[1.0, 1.5, 2.2]


El anterior es un porcedimiento muy fácil para construir listas y luego arreglos

In [15]:
r2.append(6.1)
print(r2)
r2.pop(0)
print(r2)
print(len(r2))
r2.pop(-2)
print(r2)

[1.0, 1.5, 2.2, 6.1]
[1.5, 2.2, 6.1]
3
[1.5, 6.1]


Tuplas

Sus elementos no pueden ser modificados

In [16]:
t1 = (1,1,2,3,5,8,13)
print(t1[4])
t1[4]= t1[4]+1

5


TypeError: 'tuple' object does not support item assignment

Listas y tuplas multidimensionales

In [17]:
ld2 = [[3,9],(8.5),[11,1,4]]
print(ld2)
print(ld2[2][0])

[[3, 9], 8.5, [11, 1, 4]]
11


Arreglos (NumPy arrays)

In [18]:
import numpy as np

Creación

1) array = np.array(list)

In [19]:
a1 = np.array(l1)
print(a1)
a2 = np.array(l2)
print(a2)
print(np.array([2+1j, 2., 3]))
1. + 1

[ 0  1  1  2  3  5  8 13]
['5.0' 'girl' '(5+1j)' 'horse' '21']
[2.+1.j 2.+0.j 3.+0.j]


2.0000

2) array = np.linspace(elMenor,elMayor,numeroPuntos)

 array = np.logspace(expoelMenor,expoelMayor,numeroPuntos)

In [20]:
%precision 2
a3 = np.linspace(0,10,5)
a4 = np.logspace(1,3,5)
print(a3)
print(a4)

[ 0.   2.5  5.   7.5 10. ]
[  10.     31.62  100.    316.23 1000.  ]


3) array = np.arange(elMenor,antesMayor,paso)

In [21]:
print(np.arange(0,10,2))

[0 2 4 6 8]


4) Otros

In [22]:
print(np.zeros(5,dtype = float))
print(np.ones(7,dtype = int))

[0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1]


Operaciones vectoriales, slicing

In [23]:
a5 = np.array([34, -12, 5.])
a6 = np.array([68., 5.0, 20.])
print(a5+a6)
print(a5/a6)

[102.  -7.  25.]
[ 0.5  -2.4   0.25]


In [24]:
a7 = np.linspace(-3.14,3.14,21)
print(np.cos(a7))

[-1.00e+00 -9.51e-01 -8.08e-01 -5.87e-01 -3.08e-01  7.96e-04  3.10e-01
  5.88e-01  8.09e-01  9.51e-01  1.00e+00  9.51e-01  8.09e-01  5.88e-01
  3.10e-01  7.96e-04 -3.08e-01 -5.87e-01 -8.08e-01 -9.51e-01 -1.00e+00]


In [25]:
a8 = np.array([-1., 0.,1.,2.,3.,4.,5.,10.])
print(np.log10(a8))

[ nan -inf 0.   0.3  0.48 0.6  0.7  1.  ]


/var/folders/yv/xkr121fn6sg196g8ytf0bq3m0000gn/T/ipykernel_99072/3358769065.py:2: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(a8))
/var/folders/yv/xkr121fn6sg196g8ytf0bq3m0000gn/T/ipykernel_99072/3358769065.py:2: RuntimeWarning: invalid value encountered in log10
  print(np.log10(a8))


In [26]:
y = np.array([0., 1.3, 5.,10.9,18.9,28.7,40.0])
t = np.array([0.,0.49,1.,1.5,2.08,2.55,3.2])

In [27]:
np.size(y)
np.size(t)

7

$\displaystyle v = \frac{y_i-y_{i-1}}{t_i-t_{i-1}}$

In [28]:
y[:-1]

array([ 0. ,  1.3,  5. , 10.9, 18.9, 28.7])

In [29]:
y[1:]

array([ 1.3,  5. , 10.9, 18.9, 28.7, 40. ])

In [30]:
v = (y[1:]-y[:-1])/(t[1:]-t[:-1])
print("la velocidad media es ", v)

la velocidad media es  [ 2.65  7.25 11.8  13.79 20.85 17.38]


Queremos hacer una gráfica de la velocidad media, mejor queda si lo hacemos respecto al punto medio de cada intervalo

In [31]:
tv = (t[1:]+t[:-1])/2.

In [32]:
import matplotlib.pyplot as plt

In [33]:
plt.plot(tv,v,'ro')
plt.rc('text',usetex = True)
plt.xlabel('t',fontsize = 18)
plt.ylabel('v',fontsize = 18)
plt.text(0.5,15.0,r'$\displaystyle v = \frac{y_i-y_{i-1}}{t_i-t_{i-1}}$',fontsize = 16)

Text(0.5, 15.0, '$\\displaystyle v = \\frac{y_i-y_{i-1}}{t_i-t_{i-1}}$')

Error in callback <function _draw_all_if_interactive at 0x10eff4a40> (for post_execute):


RuntimeError: Failed to process string with tex because latex could not be found

RuntimeError: Failed to process string with tex because latex could not be found

<Figure size 640x480 with 1 Axes>

Boolean Masks

In [34]:
print("Las posiciones para t > 1.5 son",y[t>1.5])

Las posiciones para t > 1.5 son [18.9 28.7 40. ]


In [35]:
print("La posicion 10.9 se alcanzó en el tiempo",t[y==10.9])

La posicion 10.9 se alcanzó en el tiempo [1.5]


# Arreglos multidimensionales y Matrices

In [59]:
lista = [[1.,4,5],[9,7,5]]

In [60]:
b = np.array(lista)
print(b)

[[1. 4. 5.]
 [9. 7. 5.]]


In [37]:
print("Número de elementos =", b.size,"Filas, columnas =", b.shape,"\nMedia de los elementos = ", b.mean())
print("Dimension de la matriz = ",b.ndim,"Mínimo de los elementos", b.min())

Número de elementos = 6 Filas, columnas = (2, 3) 
Media de los elementos =  5.166666666666667
Dimension de la matriz =  2 Mínimo de los elementos 1.0


In [38]:
a = np.ones((3,4),dtype=float)
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [40]:
c = np.arange(6)
print(c)
print("el mismo arreglo como matriz\n", np.reshape(c,(2,3)))

[0 1 2 3 4 5]
el mismo arreglo como matriz
 [[0 1 2]
 [3 4 5]]


In [41]:
print(b[0][2], b[0,2])

5.0 5.0


# Operaciones de matrices

In [42]:
print(2*b,"\n\n",b**2,"\n\n",b-2,"\n\n",np.sin(b))

[[ 2.  8. 10.]
 [18. 14. 10.]] 

 [[ 1. 16. 25.]
 [81. 49. 25.]] 

 [[-1.  2.  3.]
 [ 7.  5.  3.]] 

 [[ 0.84 -0.76 -0.96]
 [ 0.41  0.66 -0.96]]


In [43]:
d = np.reshape(c,(2,3))
print(b.shape,c.shape)
print(d)

(2, 3) (6,)
[[0 1 2]
 [3 4 5]]


In [44]:
print(b,"\n\n",d)
print("\n",b*d)

[[1. 4. 5.]
 [9. 7. 5.]] 

 [[0 1 2]
 [3 4 5]]

 [[ 0.  4. 10.]
 [27. 28. 25.]]


Cómo será la multiplicación standard  de matrices
$$f_{ij} = \sum_k b_{ik}\,g_{kj}\mbox{?}$$
El número de columnas de la matriz $b$ debe ser igual al número de filas de la matriz $g$.

In [45]:
g = np.reshape(c,(3,2))
print(g)

[[0 1]
 [2 3]
 [4 5]]


In [46]:
print(np.dot(b,g))

[[28. 38.]
 [34. 55.]]


# Diccionarios

In [47]:
room = {"Emma":309, "Jake":582, "Olivia":764}
print(room)
print("La habitación de Olivia es ",room["Olivia"])


{'Emma': 309, 'Jake': 582, 'Olivia': 764}
La habitación de Olivia es  764


d = {..., key:value,...}

In [48]:
weird = {"tank":52, 846:"horse",'bones':[23,"fox",'grass'],'phrase':"I am here"}
print(weird)
print(weird["bones"])

{'tank': 52, 846: 'horse', 'bones': [23, 'fox', 'grass'], 'phrase': 'I am here'}
[23, 'fox', 'grass']


Construcción:

In [49]:
di = {}
di["last name"]="Alberts"
di["first name"]= "Marie"
di["birthday"]= "January 27"
print(di)

{'last name': 'Alberts', 'first name': 'Marie', 'birthday': 'January 27'}


In [50]:
print(di.keys(),"\n",di.values())

dict_keys(['last name', 'first name', 'birthday']) 
 dict_values(['Alberts', 'Marie', 'January 27'])


Creación de un diccionario de una lista de tuplas pares

In [51]:
glist = [["José","México"],["Pedro","España"],["Li","China"]]
gdict = dict(glist)
print(gdict["Li"])

China


# Un ejemplito de ayuda:

In [52]:
A = [[1,3,5],[2,4,6],[1,2,3]]
print(" A = ", A)

 A =  [[1, 3, 5], [2, 4, 6], [1, 2, 3]]


Un elemento de la lista A:

In [53]:
print("A[0][2] = ", A[0][2])

A[0][2] =  5


Una fila de la lista A:

In [54]:
print(A[1])

[2, 4, 6]


Una operación adicional:

Para operar, transformemos la matriz A en un array:

In [55]:
A = np.asarray(A) #para este caso similar np.array(A)
a = np.linspace(0,1,3)
print(a)

[0.  0.5 1. ]


In [56]:
print(A[1]+a)

[2.  4.5 7. ]


In [57]:
print(A)

[[1 3 5]
 [2 4 6]
 [1 2 3]]


Finalmente obtengamos una columna

In [58]:
print(A[:,1])

[3 4 2]
