Existen procesos en la naturaleza que son naturalmente aleatorios mientras que hay otros que, a pesar de ser deterministas, son aparentemente aleatorios. 

Para simularlos en el computador necesitamos los números aleatorios.

# Números aleatorios

Generación de números pseudo-aleatorios

Generador de números aleatorios congruencial lineal
$$ x^\prime = (ax+c)\mod m $$

In [1]:
N = 100

a = 4567
c = 27

m = 100

x = 4
results = []

for i in range(N):
    x = (a*x+c)%m
    results.append(x)
    
print(results)

[95, 92, 91, 24, 35, 72, 51, 44, 75, 52, 11, 64, 15, 32, 71, 84, 55, 12, 31, 4, 95, 92, 91, 24, 35, 72, 51, 44, 75, 52, 11, 64, 15, 32, 71, 84, 55, 12, 31, 4, 95, 92, 91, 24, 35, 72, 51, 44, 75, 52, 11, 64, 15, 32, 71, 84, 55, 12, 31, 4, 95, 92, 91, 24, 35, 72, 51, 44, 75, 52, 11, 64, 15, 32, 71, 84, 55, 12, 31, 4, 95, 92, 91, 24, 35, 72, 51, 44, 75, 52, 11, 64, 15, 32, 71, 84, 55, 12, 31, 4]


In [2]:
x = 12
results = []

for i in range(N):
    x = (a*x+c)%m
    results.append(x)
    
print(results)

[31, 4, 95, 92, 91, 24, 35, 72, 51, 44, 75, 52, 11, 64, 15, 32, 71, 84, 55, 12, 31, 4, 95, 92, 91, 24, 35, 72, 51, 44, 75, 52, 11, 64, 15, 32, 71, 84, 55, 12, 31, 4, 95, 92, 91, 24, 35, 72, 51, 44, 75, 52, 11, 64, 15, 32, 71, 84, 55, 12, 31, 4, 95, 92, 91, 24, 35, 72, 51, 44, 75, 52, 11, 64, 15, 32, 71, 84, 55, 12, 31, 4, 95, 92, 91, 24, 35, 72, 51, 44, 75, 52, 11, 64, 15, 32, 71, 84, 55, 12]


In [3]:
import matplotlib.pyplot as plt 

In [4]:
import matplotlib.pyplot as plt
plt.rcParams['font.size'] = '16'
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Tahoma']
plt.rc('text',usetex = True)
#plt.rc('mathtext',fontset = 'stix')

In [28]:
N = 100
a = 1664525
c = 1013904223
m = 4294967296 #2**32
x = 134091   #semilla
results = []

for i in range(N):
    x = (a*x+c)%m
    results.append(x)
    
plt.plot(results,"o")
#print(results)
plt.ylabel(r'$/x$',fontsize = 18)
plt.xlabel(r'$/i$',fontsize = 18)
plt.show()
#print(results)


RuntimeError: Failed to process string with tex because latex could not be found

<Figure size 640x480 with 1 Axes>

#### Comentarios:

1) No son realmente aleatorios

2) Intervalo $[0,m-1]$

3) Período

4) Calidad depende de la escogencia de $a$, $c$, $m$

5) ¿Qué es la semilla?

6) **Fallas:** correlación entre valores, períodos pequeños, falta de uniformidad, paridad, etc

### Paquete random (Merssene twister)

In [6]:
from random import random, randrange, seed

random( ): genera un numero aleatorio uniformemente distribuido en el intervalo [0,1)

In [7]:
random()

0.6760240966041589

randrange(n): entero de 0 a n-1

In [8]:
print(randrange(10))
print(randrange(10))
print(randrange(10))

8
7
7


randrange(m,n,k): entero de m a n-1 cada k (se puede omitir k, default 1)

In [9]:
for i in range(100):
    print(randrange(2,20,3),end = ' ')

5 11 8 8 11 2 14 17 8 5 11 11 8 2 2 17 5 2 2 14 5 14 14 14 8 17 11 2 11 17 8 5 8 5 17 14 8 8 11 8 5 8 5 11 17 8 2 17 14 5 14 8 17 14 14 11 11 8 17 17 11 17 11 2 2 2 5 2 2 5 5 5 5 17 5 8 5 17 14 11 5 2 14 8 5 8 14 5 8 14 8 17 11 8 11 11 11 17 5 5 

Si quieres mantener la secuencia de números hay que guardarla (en principio)

La semilla $seed$ le dice al generador donde empezar la secuencia y determina la misma. Para el congruencial y muchos otros generadores es el primer número de la secuencia

In [10]:
seed(235091)
for i in range(4):
    print(randrange(10))

1
7
3
4


### Utilizando numpy

In [11]:
import numpy.random as nr
import numpy as np
import time

In [12]:
print(nr.random())

0.9035656908379934


In [13]:
print(nr.randint(100))

34


In [14]:
print(nr.randint(4,size = (2,2)))

[[3 3]
 [0 3]]


In [15]:
print(nr.rand(3, 5))

[[0.32562784 0.59178695 0.19141091 0.65409133 0.82432718]
 [0.06170583 0.25763906 0.21482155 0.29891703 0.96999333]
 [0.88430957 0.77304872 0.39569401 0.24088873 0.69618965]]


In [16]:
print(nr.choice([2,3,5,9],size = (3,5)))

[[9 2 5 5 5]
 [2 3 2 5 5]
 [3 9 9 9 3]]


In [17]:
print(nr.choice(['Juan','Abraham','Jorge'],size=(1,10)))

[['Abraham' 'Juan' 'Juan' 'Jorge' 'Abraham' 'Juan' 'Jorge' 'Jorge'
  'Jorge' 'Juan']]


In [18]:
nr.seed(125)
print(nr.random())

0.50672601149957


https://numpy.org/doc/1.16/reference/routines.random.html

### El problema del lanzamiento de una moneda sesgada. 

Queremos generar un evento con probabilidad p

In [19]:
#supongamos p = 0.2
x = random()
print(x)
if x  < 0.2:
    print("Se realiza el evento")
else:
    print("No se realiza el evento")
   

0.7837979831341545
No se realiza el evento


Ejemplo 10.1 (Mark Newman) Decaimiento de un isótopo

El radioisótopo $^{208}$Tl (thallium 208) decae al estable $^{208}$Pb (plomo 208) 
con una vida media de 3.053 min. Suponga que empezamos con una muestra de 1000 átomos
de thallium. Simulemos el decaimiento de estos átomos, mimetizando la aleatoriedad de este
decaimiento utilizando múmeros aleatorios.


De teoría se conoce que el número promedio de átomos que no ha decaído en un tiempo $t$ es :
    $$ N(t) = N(0)\, 2^{-t/\tau},$$
donde $\tau$ es el tiempo de vida media.

Fracción de átomos que permanece en  un tiempo t:  $2^{-t/\tau}$
    
Fracción de átomos que ha decaído en  un tiempo t:  $1-2^{-t/\tau} = p(t)$, 
probabilidad de decaimiento.

In [20]:
import numpy as np
import numpy.random as nr
import time

In [21]:
NTl = 100000 #Numero de atomos de Tl
NPb = 0 #Numero de atomos de Pb
h = 1  # intervalo de tiempo
tau = 3.053*60  #tiempo de vida media
p = 1 - 2**(-h/tau) #probabilidad de decaimiento

NTalios = [NTl]
NPlomos = [NPb]

tmax = 1000 
startTime = time.process_time()
for _ in range(1,tmax,h):
    
    decays = 0 #Cuenta el número de ´átomos que decayeron en el tiempo t
    for i in range(NTl):
        r = nr.random()
        if r < p: #Moneda sesgada           
            decays += 1
#    actual = nr.random(NTl) #Utilizando nimpu
#    decay = actual[actual<p].size

    NTl -= decays
    NPb += decays
    NTalios.append(NTl)
    NPlomos.append(NPb)

endTime = time.process_time()
print('tiempo = ',round(endTime-startTime,2),' s')
tpoints = np.arange(0,tmax,h)

tiempo =  3.81  s


In [22]:
print(len(NTalios),tpoints.size)

1000 1000


In [23]:
import matplotlib.pyplot as plt
plt.rcParams['font.size'] = '16'
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Tahoma']
plt.rc('text',usetex = True)

In [24]:
# Make the graph
plt.plot(tpoints,NTalios,color = "blue",label = "Tl")
plt.plot(tpoints,NPlomos,color = "red",label = "Pb")
plt.xlabel("Time",fontsize = 24)
plt.ylabel("Number of atoms",fontsize = 24)
plt.legend(loc = 'center right')
#plt.show()

Error in callback <function _draw_all_if_interactive at 0x120ed34c0> (for post_execute), with arguments args (),kwargs {}:


RuntimeError: Failed to process string with tex because latex could not be found

RuntimeError: Failed to process string with tex because latex could not be found

<Figure size 640x480 with 1 Axes>

In [25]:
plt.semilogy(tpoints,NTalios,color = "blue",label = "Tl")
plt.xlabel("Time",fontsize = 24)
plt.ylabel("Number of atoms",fontsize = 24)
plt.legend(loc = 'center right')
plt.show()

RuntimeError: Failed to process string with tex because latex could not be found

<Figure size 640x480 with 1 Axes>

¿Cómo a partir de esta cuerva estimamos el tiempo de vida media?

## Mínimos Cuadrados

Minimizo:
$$ S = \sum_{i=0}^{n-1} [ y_i - f(x_i, a, b, c, \cdots )]^2$$

Ajuste lineal:

$$ f(x;a,b,c,\cdots) = y = b\,x + a$$

Solución:
$$\displaystyle b = \frac{\sum_i (x_i -\bar{x})y_i}{\sum_i (x_i -\bar{x})x_i}, \qquad a = \bar{y} - b\bar{x} $$

donde
$$ \bar{x} = \frac{1}{n}\sum_i x_i, \;
\bar{y} = \frac{1}{n}\sum_i y_i$$

In [26]:
def lineFit(x, y):
    ''' Returns slope and y-intercept of linear fit to (x,y)
    data set'''
    xavg = x.mean()
    slope = (y * (x - xavg)).sum() / (x * (x - xavg)).sum()
    yint = y.mean() - slope * xavg
    return slope, yint

In [27]:
t,v,s = np.loadtxt("VelocityVsTimeData.txt",skiprows = 3,usecols = (0,1,2),unpack = True)

FileNotFoundError: VelocityVsTimeData.txt not found.

In [ ]:
a, v0 = lineFit(t,v)
print(v0,a)
print(abs((a-(-9.8))/(-9.8))*100)

In [ ]:
# create plot
plt.figure(1, figsize=(6, 4))
plt.errorbar(t, v, fmt='oC1', label="data",
             yerr=s, ecolor='black')
plt.plot(t,v0+a*t,'blue', label = 'linear fit')
#plt.plot(t,v0ince+ainc*t,'red', label = 'linear fit 2')
plt.xlabel(r'$t$')
plt.ylabel(r'$v$')
plt.legend(loc='upper right')

# display plot on screen
plt.show()


### Mínimos cuadrados lineal con incertidumbre en la data

Tomando en cuenta la incertidumbre de la data, minimizamos
$$ \displaystyle \chi^2 = \sum_{i=0}^{n-1} \left [\frac{ y_i - f(x_i, a, b, c, \cdots )}{\sigma_i}\right]^2$$
Solución para el caso lineal:
$$\displaystyle b = \frac{\sum_i (x_i -\hat{x})y_i/\sigma_i^2}{\sum_i (x_i -\hat{x})x_i/\sigma_i^2}, \qquad a = \hat{y} - b\hat{x} $$

donde
$$ \hat{x} = \frac{\sum_i x_i/\sigma_i^2}{\sum_i 1/\sigma_i^2} 
, \;
\hat{y} = \frac{\sum_i y_i/\sigma_i^2}{\sum_i 1/\sigma_i^2}$$


#### Parámetro chi-cuadrado reducido

\begin{equation}
\chi_r^2 = \frac{\chi^2}{n-2}
\end{equation}

$\chi_r^2 \approx 1$: fit óptimo

$\chi_r^2 \gg 1$: fit pobre

$\chi_r^2 \ll 1$: incertidumbre sobre estimada

#### Errores de los fits

\begin{equation}
\sigma_b^2 = \left [\sum_i (x_i - \hat{x})x_i/\sigma_i^2 \right ]^{-1}
\end{equation}

\begin{equation}
\sigma_a^2 = \sigma_b^2  \displaystyle \frac{\sum_i x_i^2/\sigma_i^2}{\sum_i 1/\sigma_i^2}  
\end{equation}

In [ ]:
from IPython.display import Image
Image(filename = "AjusteExponencial.png",width = 800)

## Auste no lineal (Pine)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['font.size'] = '16'
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Tahoma']
plt.rc('text',usetex = True)

In [ ]:
f, s, ds = np.loadtxt("Spectrum.txt", skiprows=4,
                      unpack=True)
plt.errorbar(f, s, yerr=ds, fmt='oC3', ecolor='black')
plt.ylabel('absorción',fontsize = 18)
plt.xlabel(r'$\nu$',fontsize = 18)

### Argumentos de la función curve_fit de la librería scipy.optimize

In [ ]:
from IPython.display import Image
Image(filename = "curvefitarguments.png",width = 600,height = 600)

\begin{equation}
Abs(\nu) = a + b\,\nu + c\,\nu^2+P\,\mbox{e}^{\displaystyle -0.5((\nu-\nu_p)/\nu_w)^2}
\end{equation}

In [ ]:
from IPython.display import Image
Image(filename = "nolineal.png",width = 600)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec  # unequal plots
import scipy.optimize


# define fitting function
def GaussPolyBase(f, a, b, c, P, fp, fw):
    return a + b * f + c * f * f + P * np.exp(-0.5 * ((f - fp) / fw) ** 2)


# read in spectrum from data file
# f=frequency, s=signal, ds=s uncertainty
f, s, ds = np.loadtxt("Spectrum.txt", skiprows=4,
                      unpack=True)

# initial guesses for fitting parameters
a0, b0, c0 = 60., -3., 0.
P0, fp0, fw0 = 80., 11., 2.

# fit data using SciPy's Levenberg Marquart method
nlfit, nlpcov = scipy.optimize.curve_fit(GaussPolyBase,
                                         f, s, p0=[a0, b0, c0, P0, fp0, fw0],
                                         sigma=ds)

# unpack fitting parameters
a, b, c, P, fp, fw = nlfit
# unpack uncertainties in fitting parameters from
# diagonal of covariance matrix
da, db, dc, dP, dfp, dfw = [np.sqrt(nlpcov[j, j])
                            for j in range(nlfit.size)]

# create fitting function from fitted parameters
f_fit = np.linspace(0.0, 25., 128)
s_fit = GaussPolyBase(f_fit, a, b, c, P, fp, fw)

# Calculate residuals and reduced chi squared
resids = s - GaussPolyBase(f, a, b, c, P, fp, fw)
redchisqr = ((resids / ds) ** 2).sum() / float(f.size - 6)

# Create figure window to plot data
fig = plt.figure(1, figsize=(9.5, 6.5))
gs = gridspec.GridSpec(2, 1, height_ratios=[6, 2])

# Top plot: data and fit
ax1 = fig.add_subplot(gs[0])
ax1.plot(f_fit, s_fit, '-C0')
ax1.errorbar(f, s, yerr=ds, fmt='oC3', ecolor='black')
#ax1.set_xlabel('frequency (THz)',fontsize = 18)
ax1.set_ylabel('absorption (arb units)',fontsize = 18)
ax1.text(0.7, 0.95, r'$a = {0:0.1f}\pm${1:0.1f}'
         .format(a, da), transform=ax1.transAxes)
ax1.text(0.7, 0.88, r'$b = {0:0.2f}\pm${1:0.2f}'
         .format(b, db), transform=ax1.transAxes)
ax1.text(0.7, 0.81, r'$c = {0:0.2f}\pm${1:0.2f}'
         .format(c, dc), transform=ax1.transAxes)
ax1.text(0.7, 0.74, r'$P = {0:0.1f}\pm${1:0.1f}'
         .format(P, dP), transform=ax1.transAxes)
ax1.text(0.7, 0.67, r'$f_p = {0:0.1f}\pm${1:0.1f}'
         .format(fp, dfp), transform=ax1.transAxes)
ax1.text(0.7, 0.60, r'$f_w = {0:0.1f}\pm${1:0.1f}'
         .format(fw, dfw), transform=ax1.transAxes)
ax1.text(0.7, 0.53, r'$\chi_r^2$ = {0:0.2f}'
         .format(redchisqr), transform=ax1.transAxes)
ax1.set_title(r'$s(f)=a+bf+cf^2+P\,e^{-(f-f_p)^2/2f_w^2}$')

# Bottom plot: residuals
ax2 = fig.add_subplot(gs[1])
ax2.errorbar(f, resids, yerr=ds, ecolor="black",
             fmt="oC3")
ax2.axhline(color="gray", zorder=-1)
ax2.set_xlabel('frequency (THz)',fontsize = 18)
ax2.set_ylabel('residuals',fontsize = 18)
ax2.set_ylim(-20, 20)
ax2.set_yticks((-20, 0, 20))

fig.savefig("FitSpectrum.pdf")
plt.show()



## Integración de Monte Carlo

In [ ]:
import numpy as np
import time

\begin{equation}
I = \int_0^{3.5} \, \mbox{e}^{-x^2}\,dx = \frac{\sqrt{\pi}}{2} \mbox{erf}(3.5) \approx 0.8862262668989721
\end{equation}

In [ ]:
funcion1 = lambda x: np.exp(-x**2)  
a = 0
b = 3.5

In [ ]:
Iexacto = 0.8862262668989721

In [ ]:
x = np.linspace(0,4,100) 
plt.plot(x,funcion1(x),color = 'black')
plt.fill_between(x,funcion1(x),alpha=0.5)
plt.xlabel(r'$x$',fontsize = 18)
plt.ylabel(r'$f(x)$',fontsize = 18)
plt.ylim(0,1.1)
plt.xlim(0,4)
plt.axvline(3.5,color = 'gray', dashes = (3,1))
plt.axhline(1,color = 'gray', dashes = (3,1))

### 1) Asertar y Fallar

Queremos resolver

\begin{equation}
I = \int_a^b f(x)\, dx 
\end{equation}

1. Generamos $N$ puntos $(x,y)$ al azar dentro del rectángulo de área $A$ limitado por el máximo de la función y por los límites de integración.
2. Contamos el número de puntos $k$ que caen en el área bajo la curva $y < f(x)$
3. Si $p$ es la probabilidad de caer bajo la curva tenemos:
\begin{equation}
p = \frac{I}{A} \approx \frac{k}{N}, \quad \Rightarrow \quad I \approx \frac{k A}{N}
\end{equation}

In [ ]:
def AsertarFallar(f,a,b,c,N,*args):
    count = 0
    for i in range(N):
        x = (b-a)*np.random.random()+a
        y = c*np.random.random()
        if y<f(x,*args):
            count += 1
    I = (b-a)*c*count/N
    return I    

In [ ]:
startTime = time.process_time()
c = 1
N = 10000000
I = AsertarFallar(funcion1,a,b,c,N)
eabs = np.abs(I-Iexacto)
endTime = time.process_time()
print('I = ',I,'eabs = ',eabs,'erel = ',eabs/np.abs(Iexacto))
print('tiempo de computo = ',round(endTime-startTime,2),' s')

### Asertar y Fallar (numpy)

In [ ]:
def npAsertarFallar(f,a,b,c,N,*params):
    x = (b-a)*np.random.random(N)+a
    y = c*np.random.random(N)
    parcial = y < f(x)
    
    I = (b-a)*c*(parcial[parcial==True].size)/N
    return I

In [ ]:
startTime = time.process_time()
c = 1
N = 10000000
I = npAsertarFallar(funcion1,a,b,c,N)
eabs = np.abs(I-Iexacto)
endTime = time.process_time()
print('I = ',I,'eabs = ',eabs,'erel = ',eabs/np.abs(Iexacto))
print('tiempo de computo = ',round(endTime-startTime,2),' s')

In [ ]:
def np2AsertarFallar(f,a,b,c,N,*params):
    x = (b-a)*np.random.random(N)+a
    y = c*np.random.random(N)
    y = y[y < f(x)]
    
    I = (b-a)*c*(y.size)/N
    return I

In [ ]:
startTime = time.process_time()
c = 1
N = 10000000
I = np2AsertarFallar(funcion1,a,b,c,N)
eabs = np.abs(I-Iexacto)
endTime = time.process_time()
print('I = ',I,'eabs = ',eabs,'erel = ',eabs/np.abs(Iexacto))
print('tiempo de computo = ',round(endTime-startTime,3),' s')

#### En general los métodos de integración de Montecarlo no son buenos

Problema Binomial

$p = I/A$: probabilidad de acertar

$1-p$ : probabilidad de fallar

Probabilidad de acertar despues de $N$ lanzamientos:
\begin{equation}
P(k) = \left ( N \atop k \right ) p^k (1-p)^{N-k}
\end{equation}

media: $\langle k \rangle = N p$

varianza = $\sigma_k^2 = \langle k^2 \rangle - \langle k \rangle^2 = Np(1-p)$

Por lo tanto el error 

\begin{equation}
\sigma_I = \sigma_k \frac{A}{N} = \frac{A}{N} \sqrt{N \frac{I}{A} \left ( 1- \frac{I}{A}\right)} = \frac{\sqrt{I(A-I}}{N^{1/2}}
\end{equation}

#### Error de los métodos convencionales

Trapecio: $N^{-2}$

Simpson: $N^{-4}$

## 2) El método del valor medio

\begin{equation}
\langle f \rangle = \frac{1}{b-a}\int_a^b f(x)\, dx = \frac{I}{b-a}, \quad \Rightarrow \quad I = (b-a)\, \langle f \rangle
\end{equation}

1) Generamos $N$ coordenadas $x$ al azar

2) Evaluamos la función $f(x)$ en esas coordenadas y promediamos

\begin{equation}
\langle f \rangle \approx \frac{1}{N}\sum_{i=1}^{N} f(x_i)
\end{equation}

3) El valor aproximado de la integral será

\begin{equation}
I \approx \frac{b-a}{N}\sum_{i=1}^{N} f(x_i)
\end{equation}

#### Se puede demostrar que el error es también del orden $N^{-1/2}$

\begin{equation}
\sigma_I = \frac{b-a}{N}\sigma_{\mbox{suma}} = \frac{b-a}{N} \sqrt{N \mbox{Var}(f)} = \frac{(b-a)\sigma_f}{N^{1/2}}
\end{equation}

## 3) Integrales en múltiples dimensiones

Funciona, en general, mejor que los métodos convencionales donde se necesitan $N^d$ subdivisiones

Se quiere resolver:
    
\begin{equation}
I = \int_{V} f(\vec{r})\, d\vec{r}
\end{equation}

La fórmula del valor medio queda como

\begin{equation}
I \approx \frac{V}{N} \sum_{i=1}^N f(\vec{r}_i)
\end{equation}

$\vec{r}_i$: generados al azar en el hipervolumen de integración $V$ (dominio)

Ejemplo: Volumen de una hiperesfera en 10 dimensiones. En dos dimensiones sería:

In [ ]:
from IPython.display import Image
Image(filename = "Volumen.png",width = 400)

\begin{equation}
I = \int_{-1}^1\int_{-1}^1 f(x,y)\,dxdy
\end{equation}

donde

\begin{equation}
f(x,y) = \left \{ 1 \quad \mbox{si} \quad x^2+y^2 \le 1  \atop 0 \quad \mbox{si} \quad x^2+y^2 > 1 \right .
\end{equation}

El volumen aproximado será:

\begin{equation}
I \approx \frac{4}{N} \sum_{i=1}^N f(x_i,y_i)
\end{equation}

Solución exacta:

Volumen de una esfera en $d$ dimensiones
$$v_d = \frac{\pi^{d/2}R^d}{\Gamma(d/2+1)}$$

In [ ]:
import numpy as np
import time

In [ ]:
startTime = time.process_time()
d = 10
N = 10000000

r = np.random.uniform(-1,1,(N,d)) #Genera N vectores de simension d

r2 = (r*r).sum(axis =1)
print(r2.shape)
#r2 = np.linalg.norm(r,axis = 1)
                       
I = 2**d*r2[r2<1].size/N

from scipy.special import gamma

Iexacto = np.pi**(d/2)/gamma(d/2+1)

erel = abs((I-Iexacto)/Iexacto)
print('I = ',I,'Iexacto =',Iexacto,'erel = ',erel)

endTime = time.process_time()
print('Duración= {} s.'.format(endTime-startTime))

Utilizando un método convencional si quisieramos un subdivisión de 100 por eje, necesitaríamos $100^{10} = 10^{20}$ puntos en total (imposible para computadoras actuales). Nos bastan $10^6$ puntos en Montecarlo para un buen resultado.

## 4) Muestreo de importancia

In [ ]:
import numpy as np
import time

In [ ]:
import matplotlib.pyplot as plt
plt.rcParams['font.size'] = '16'
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Tahoma']
plt.rc('text',usetex = True)

Queremos resolver la siguiente integral

\begin{equation}
I = \int_0^1 \frac{x^{-1/2}}{e^x+1}\,dx \quad \mbox{gases de Fermi}
\end{equation}

La contribución a la integral de los valores de $x$ cercanos a 0 es grande en comparación con los del resto del intervalo.

La idea es utilizar un método de Montecarlo donde en lugar de generar los números al azar de manera uniforma, se generan con una distribución donde salgan más números en la cercanía del origen.

¿Cómo se hace?

In [ ]:
funcion2 = lambda x: x**(-0.5)/(np.exp(x)+1)  
a = 0
b = 1
funcion3 = lambda x: x**(-1)/(np.exp(x)+1)  

In [ ]:
x = np.linspace(0.01,1.5,150)

In [ ]:
plt.plot(x,funcion2(x),label = r'$f(x) = \displaystyle \frac{1}{x^{1/2}(e^x+1)}$')
plt.plot(x,funcion3(x),'r',label = r'$f(x) = \displaystyle \frac{1}{x(e^x+1)}$')
plt.xlabel(r'$x$',fontsize = 18)
plt.ylabel(r'$f(x)$',fontsize = 18)
plt.axvline(1,color = 'gray',dashes = (3,1))
plt.axvline(0,color = 'gray',dashes = (3,1))
plt.legend(loc = 'best',fontsize = 12)
maximo = funcion2(x).max()
plt.ylim(0,maximo)

Promedio ponderado de una función $g$ por un peso $w$

\begin{equation}
\langle g \rangle_w = \frac{\int_a^b w(x) g(x)\,dx}{\int_a^b w(x)\,dx}
\end{equation}

Queremos resolver:

\begin{equation}
I = \int_a^b f(x)\,dx
\end{equation}

Si $g(x) = f(x)/w(x)$ tenemos:

\begin{equation}
\left \langle \frac{f}{w} \right \rangle_w = \frac{\int_a^b f(x)\,dx}{\int_a^b w(x)\,dx}
\end{equation}

Por lo tanto:

\begin{equation}
\boxed{I = \left \langle \frac{f}{w} \right \rangle_w \int_a^b w(x)\,dx}
\end{equation}

Para hacer esto:

\begin{equation}
\left \langle \frac{f}{w} \right \rangle_w \approx \frac{1}{N}\sum_{i=1}^N \frac{f(x_i)}{w(x_i)},
\end{equation}

donde los $x_i$ son números al azar generados a partir de  la distribución:

\begin{equation}
p(x) = \frac{w(x)}{\int_a^b w(x)\,dx}
\end{equation}

### Generación de números aleatorios no uniformes


Distribución uniforme en el intervalo $[a,b)$. La probabilidad de que un punto tomado al azar caiga entre $x$ y $x+dx$ es:

\begin{equation}
p(x)\,dx = \frac{1}{b-a}\,dx
\end{equation}

#### Método de la transformación

1) Se tiene una fuente de números flotantes aleatorio $z$ distribuidos por la densidad de probabilidad $q(z)$. $q(z)\,dz$ es la probabilida de generar un número al alzar entre $z$ y $z+dz$.

2) Se tiene una función $x(z)$. Como $z$ es un número aleatorio $x(z)$ también lo será pero con un distribución $p(x)$

3) Propósito del método de la transformación: Conseguir la función $x(z)$ que nos de la distribución que queremos.

4) Se cumple: $p(x)\,dx = q(z) \, dz$

5) En general se utiliza $q(z)$ como una distribución uniforme en el intervalo $[0,1)$. Integrando la expresión del punto 4) tenemos:

\begin{equation}
\int_{x_0}^{x(z)} p(x^\prime)\,dx^\prime = \int_0^z\, dz^\prime = z
\end{equation}

6) La idea es hacer la integral de la izquierda y  despejar $x(z)$. No siempre se puede.

#### Ejemplo decaimiento del Talium

La probabilidad de decaimiento en un tiempo $dt$ es 
\begin{equation}
p = 1 - 2^{-\displaystyle\frac{dt}{\tau}} = 1- \exp\left (-\frac{dt}{\tau} \ln 2 \right ) = \frac{\ln 2}{\tau}\,dt
\end{equation}

donde despreciamos términos del orden $dt^2$.

Probabilidad de que un átomo decaiga en el intervalo entre $t$ y $t+dt$ es:

\begin{equation}
P(t)dt = 2^{-\displaystyle\frac{t}{\tau}}\frac{\ln 2}{\tau}\,dt= \frac{\ln 2}{\tau} \mbox{e}^{\displaystyle -t\ln 2/\tau}\,dt
\end{equation}

**Distribución exponencial**

\begin{equation}
p(x)\,dx = \mu \mbox{e}^{-\mu x}\,dx
\end{equation}

In [ ]:
Image(filename = "decayexpo.png",width = 600)

#### Método de la transformación

\begin{equation}
\mu \int_0^{x(z)} \mbox{e}^{-\mu x^\prime}\,dx^\prime= 1 - \mbox{e}^{-\mu x} = z
\end{equation}

Por lo tanto

\begin{equation}
x = -\frac{1}{\mu}\ln (1 - z)
\end{equation}

$z$ generados de manera uniforme nos da $x$ distribuidos exponencialmente. Para nuestro caso $\mu = \ln 2/\tau$

In [ ]:
Image(filename = "Tdecays.png",width = 400)

In [ ]:
def expoDistribution(mu,N):
    x = -np.log(1-np.random.random(N))/mu
    return x   

In [ ]:
tmax = 1000 # Total time
h = 1.       # Paso de tiempo
tau = 3.053*60   # tiempo de vida media

# Lists of plot points
tpoints = np.arange(0.0,tmax,h)

#Generación de los 1000 números al azar, representa los tiempos de deciamiento 
N = 100000 #Numero inical de atomos de Tallium

startTime = time.process_time()
Tdecays = expoDistribution(np.log(2)/tau,N)

#Generación de la función que nos da el número de Tl que no han decaido
NTall = []
t0 = 0.
for i in range(1000):
    NTall.append(Tdecays[Tdecays>t0].size)
    t0 += h

endTime = time.process_time()
print('Duración= {} s.'.format(endTime-startTime))


In [ ]:
plt.semilogy(NTall)
#plt.plot(NTall)
plt.xlabel(r'$t$',fontsize = 18)
plt.ylabel('NTallilum',fontsize = 18)
tpoints=np.array(tpoints)
NTall = np.array(NTall)
print(tpoints.size,NTall.size)

# Caminante aleatorio

## Caminante aleatorio en una dimensión

In [ ]:
from IPython.display import Image
Image(filename = "Caminante_d=1.png",width = 800)

* A lo largo de una línea
* El caminante empieza en $x=0$
* Cada paso de igual longitud $a=1$
* $p$: probabilidad de que el paso sea hacia la derecha ($x>0$)
* $q = 1-p$: probabilidad de que el paso sea hacia la izquierda ($x<0$)
* No hay memoria. Cada paso es independiente del anterior.

¿Dónde se encontrará el caminante después de $N$ pasos?

In [ ]:
import numpy as np
import numpy.random as nr
import time
from  random import random,seed,randrange

In [ ]:
def lineFit(x, y):
    ''' Returns slope and y-intercept of linear fit to (x,y)
    data set'''
    xavg = x.mean()
    slope = (y * (x - xavg)).sum() / (x * (x - xavg)).sum()
    yint = y.mean() - slope * xavg
    return slope, yint

In [ ]:
import matplotlib.pyplot as plt
plt.rcParams['font.size'] = '14'
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Tahoma']
plt.rc('text',usetex = True)

In [ ]:
startTime = time.process_time()
N=1000000 #Numero de pasos
p = 0.5 #probabilidad de dar un paso hacia la derecha 

X = np.zeros(N+1) # Incluyo el cero
X2 = np.zeros(N+1)

x = 0.         # Start at origin. Desplazamiento respecto a la posición inicial
X[0] = x
X2[0] = x*x

for i in range(1, N+1):
    #Paso a la derecha con probabilidad p
    if nr.random() < p:
#   if random() < p: 
        x += 1.    
    else:
        x -= 1.
    X[i] = x
    X2[i] = x*x
endTime = time.process_time()
print('tiempo de corrida: ',round(startTime-endTime,2),' s')

In [ ]:
plt.figure(figsize = (5,5))
plt.plot(X,'b-')
plt.xlabel('pasos',fontsize = 18)
plt.ylabel(r'$x$',fontsize = 18)

### Alternativa para el caso $p=0.5$

In [ ]:
N=100000

X = np.zeros(N+1)
X2 = np.zeros(N+1)

x = 0.         # Start at origin
X[0] = x
X2[0] = x*x

for i in range(1, N+1):
#    x += randrange(-1,2,2)   #Solamente válido para p = 0.5
    x += nr.choice([-1,1])
    
    X[i] = x
    X2[i] = x*x

In [ ]:
plt.figure(figsize = (5,5))
plt.plot(X,'b-')
plt.xlabel('pasos',fontsize = 18)
plt.ylabel(r'$x$',fontsize = 18)

### Utilizando numpy

In [ ]:
startTime = time.process_time()
N = 1000000
p= 0.5 #Este sirve para cualquier p

x=nr.rand(N) #Desplazamientos 
x[x<p] = 1 #Desplazamientos a la derecha
x[x != 1] = -1 #Desplazamientos a la derecha

X=np.cumsum(x) #Posición para i pasos

X = np.append(0.,X) 
X2=X**2

endTime = time.process_time()
print('tiempo de corrida: ',round(startTime-endTime,2),' s')

In [ ]:
plt.figure(figsize = (5,5))
plt.plot(X,'b-')
plt.xlabel('pasos',fontsize = 18)
plt.ylabel(r'$x$',fontsize = 18)

### Análisis

Posición promedio para $N$ pasos:

\begin{equation}
\langle X \rangle = N (p-q) a
\end{equation}

Desplazamiento cuadrático medio

\begin{equation}
\Delta X^2 = \langle X^2 \rangle - \langle X \rangle^2 = 4 p q N \sigma^2
\end{equation}

donde $\sigma^2$ es el desplazamiento cuadrático medio se un solo paso

Probabilidad de que después de $N$ pasos el caminante se encuentre en la posición $x$
\begin{equation}
P(N,x)  = \left ( N \atop \frac{N+x}{2} \right) \frac{1}{2^N}
\end{equation}

Para $N$ grandes

\begin{equation}
P(N,x)  = \frac{1}{\sqrt{2\pi N}} \mbox{e}^{-x^2/2N}
\end{equation}

### Para comprobar esta hay que hacer muchas muestras (muchos caminates)

In [ ]:
Image(filename='Camnumpyd1.png',width=400)

In [ ]:
def CamAlead1(N,M,p):
    # N: Número total de pasos
    # M: Número de caminantes
    # p: probabilidad de paso a la derecha
    dx =np.random.rand(M,N)

    dx[dx<p] = 1
    dx[dx != 1] = -1

    X=np.cumsum(dx,axis=1)
    X2=X**2

    XparaN = X[:,N-1]

    X = X.mean(axis=0)
    X2 = X2.mean(axis=0)

    X = np.append(0.,X)
    X2 = np.append(0.,X2)
    DX2 = X2 - X*X 
    return X,DX2,XparaN

In [ ]:
startTime = time.process_time()
N = 10000 #numero de pasos del caminante
trials = 100000  #numero de realizaciones
p = 0.5 #probabilidad de paso a la derecha

X,DX2,XparaN = CamAlead1(N,trials,p)

endTime = time.process_time()
print('Duración= {} s.'.format(endTime-startTime))

In [ ]:
plt.figure(figsize = (5,5))
plt.plot(DX2,label = r'$\Delta X^2$')
plt.plot(X,label = r'$\langle X \rangle$')
plt.xlabel(r'$N$',fontsize = 18)

t = np.arange(0,N+1)

slope, corte = lineFit(t,DX2)
plt.plot(t,slope*t+corte,color = 'red',label = r'$\Delta X^2 = A\, N$')
print('slope = ',slope)
print('corte = ',corte)
plt.legend(loc = 'upper left',fontsize = 12)


plt.figure(figsize = (9,5))
n, bins, patches = plt.hist(XparaN, bins = 50,density = True) # density = True, funcion de distribucion

x = np.arange(-400,400,0.1)
Prob = np.exp(-x**2/(2*N))/np.sqrt(2*np.pi*N)
plt.text(100,0.75*n.max(),r'$ P(x) = \displaystyle\frac{1}{\sqrt{2\pi N}}\,\mbox{e}^{\displaystyle -x^2/2N}$',fontsize = 16)
plt.plot(x,Prob,color = 'black')
plt.xlabel(r'$x$',fontsize = 18)
plt.ylabel(r'$P(x)$',fontsize = 18)
plt.show()

## Caminante aleatorio en dos dimensiones

In [ ]:
from IPython.display import Image, display
Image(filename='Caminante.png',width=600, height=400)

\begin{equation*}
R^2 = (\Delta x_1 + \cdots + \Delta x_N )^2 + (\Delta y_1 + \cdots + \Delta y_N )^2 
\end{equation*}

Promediando para muchos caminantes

\begin{eqnarray*}
\langle R^2 \rangle  &=& \langle \Delta x_1^2 + \Delta y_1 ^2 + \cdots + \Delta x_N^2 + \Delta y_N^2 \rangle \\
&=& \langle \Delta x_1^2 + \Delta y_1 ^2 \rangle + \cdots + \langle \Delta x_N^2 + \Delta y_N^2 \rangle \\
&=& N \langle r^2 \rangle
\end{eqnarray*}

esto no es otra cosa que:

\begin{equation*}
R_\mbox{rms}^2 = N r_\mbox{rms}^2
\end{equation*}

In [ ]:
Image(filename='Caminante_d=2.png',width=400, height=400)

In [ ]:
from IPython.display import Image, display
Image(filename='DescripcionProgd2.png',width=800, height=1200)

In [ ]:
# dir determina la direccion del movimiento 0,1,2,3
# dx, dy: desplazamientos en x y y
# X,Y: posiciones en x y y
# Xmean, Ymean: posiciones medias
# R2 desplazamiento cuadrático
import time

startTime = time.process_time()
trials,N = 100000, 1024 #trials es lo mismo que numero de caminantes
dir = np.random.randint(4, size=(trials, N))
dx = np.zeros((trials, N),dtype = "int")
dy = np.zeros((trials, N),dtype = "int")
dx[dir==0],dx[dir==1],dx[dir==2],dx[dir==3]=1,0,-1,0
dy[dir==0],dy[dir==1],dy[dir==2],dy[dir==3]=0,1,0,-1
del dir

X,Y  = np.cumsum(dx,axis=1),np.cumsum(dy,axis=1)
del dx,dy
Xmean, Ymean = np.mean(X,axis = 0),np.mean(Y,axis = 0)

R2 = ((X*X).mean(axis=0)-Xmean**2) + ((Y*Y).mean(axis=0)-Ymean**2)

endTime = time.process_time()
print('Duración= {} s.'.format(endTime-startTime))

In [ ]:
plt.figure(figsize = (5,5))
Ngraf = np.arange(1,N+1)
plt.plot(Ngraf,R2)
slope, corte = lineFit(Ngraf,R2)
plt.ylabel(r'$R_{rms}^2$',fontsize = 18)
plt.xlabel(r'$N$',fontsize = 18)
plt.rc('text', usetex=True)
plt.text(700,200,r'$R_{rms}^2 = r_{rms}^2 N$',fontsize = 14)
plt.text(700,100,r'$r_{rms}^2 = $'+'{:.2f}'.format(slope))
ajuste = slope*Ngraf + corte
plt.plot(Ngraf,ajuste,'r-',dashes = (2,1))
print(slope,corte)

In [ ]:
plt.figure(figsize = (5,5))
plt.plot(Ngraf,Xmean,label =r'$\langle X \rangle$')
plt.plot(Ngraf,Ymean,'r',label =r'$\langle Y \rangle$')
plt.ylabel(r'$\langle X,Y \rangle$',fontsize = 18)
plt.xlabel(r'$N$',fontsize = 18)
plt.legend(loc = 'best',fontsize = 12)

In [ ]:
def CamAleaSquare(N,trials):
    # N: Número total de pasos
    # M: Número de caminantes
    dir = np.random.randint(4, size=(trials, N))
    dx = np.zeros((trials, N),dtype = "int")
    dy = np.zeros((trials, N),dtype = "int")
    dx[dir==0],dx[dir==1],dx[dir==2],dx[dir==3]=1,0,-1,0
    dy[dir==0],dy[dir==1],dy[dir==2],dy[dir==3]=0,1,0,-1
    del dir

    X,Y  = np.cumsum(dx,axis=1),np.cumsum(dy,axis=1)
    del dx,dy
    Xmean, Ymean = np.mean(X,axis = 0),np.mean(Y,axis = 0)

    R2 = ((X*X).mean(axis=0)-Xmean**2) + ((Y*Y).mean(axis=0)-Ymean**2)
    
    XparaN = X[:,N-1]
    YparaN = Y[:,N-1]
    
    return Xmean,Ymean,R2,XparaN,YparaN

In [ ]:
startTime = time.process_time()
trials,N = 100000, 1024 #trials es lo mismo que numero de caminantes
Xmean,Ymean,R2,XparaN,YparaN = CamAleaSquare(N,trials)
endTime = time.process_time()
print('Duración= {} s.'.format(endTime-startTime))

In [ ]:
Ngraf = np.arange(1,N+1)
fig = plt.figure(figsize = (14,14))
ax1 = fig.add_subplot(2,2,1)
ax1.plot(Ngraf,Xmean,'b',label = r'$\langle X \rangle$')
ax1.plot(Ngraf,Ymean,'r',label = r'$\langle Y \rangle$')
ax1.legend(loc = 'best',fontsize = 12)
ax1.set_xlabel(r'$N$',fontsize = 18)

ax2 = fig.add_subplot(2,2,2)
slope, corte = lineFit(Ngraf,R2)
ajuste = slope*Ngraf + corte
ax2.plot(Ngraf,R2,'b',label = r'data')
ax2.plot(Ngraf,ajuste,color = 'red',dashes = (5,1),label = r'fit')
ax2.legend(loc = 'best',fontsize = 12)
ax2.set_xlabel(r'$N$',fontsize = 18)
ax2.set_ylabel(r'$R_{rms}^2$',fontsize = 18)
print(slope,corte)

ax3 = fig.add_subplot(2,2,3)

ax3.set_xlabel(r'$x$',fontsize = 18)
ax3.set_ylabel(r'$P(x)$',fontsize = 18)
n, bins, patches = plt.hist(XparaN, bins = 50,density = True) # density = True, funcion de distribucion
x = np.arange(-400,400,0.1)
Prob = np.exp(-x**2/(2*N/2))/np.sqrt(np.pi*2*N/2)
ax3.set_xlim(-100,100)
ax3.plot(x,Prob,color = 'black')
ax3.text(0,n.max(),
         r'$ P(x) = \displaystyle\frac{1}{\sqrt{2\pi (N/2)}}\,\mbox{e}^{\displaystyle -x^2/2 (N/2)}$',
         fontsize = 13)
ax4 = fig.add_subplot(2,2,4)

ax4.set_xlabel(r'$y$',fontsize = 18)
ax4.set_ylabel(r'$P(y)$',fontsize = 18)
n, bins, patches = plt.hist(YparaN, bins = 50,density = True) # density = True, funcion de distribucion
x = np.arange(-400,400,0.1)
Prob = np.exp(-x**2/(2*N/2))/np.sqrt(np.pi*2*N/2)
ax4.set_xlim(-100,100)
ax4.plot(x,Prob,color = 'black')
ax4.text(0,n.max(),
         r'$ P(y) = \displaystyle\frac{1}{\sqrt{2\pi (N/2)}}\,\mbox{e}^{\displaystyle -y^2/2 (N/2)}$',
         fontsize = 13)
fig.tight_layout()

¿Por qué el $N/2$ en la función?

En la fórmula de la Gaussiana debería de estar la varianza de la variable aleatoria. Para la variavle aleatoria $X$ deberia estar $\Delta X^2$ y para $Y$, $\Delta Y^2$.

Sabemos que:
\begin{equation}
R^2 = \Delta X^2 + \Delta Y^2,
\end{equation}
como $R^2=N$ y hay simetría $X\leftrightarrow Y$ se tiene:
\begin{equation}
\Delta X^2 = \Delta Y^2 = N/2
\end{equation}

## Red triangular

In [ ]:
Image(filename='triangular.png',width=800, height=1200)

In [ ]:
Nb=8192
Ns =336
Nprime = 8192**(2/3)*336**(1/3)
print(Nprime)
N2 = 896

In [ ]:
print((np.log(Nb)-np.log(Nprime))/3,
     (np.log(Nprime)-np.log(N2))/3,
     (np.log(N2)-np.log(Ns))/3)

In [ ]:
np.log(Nb)

In [ ]:
np.log(Nprime)

In [ ]:
np.log(N2)